# Generated by Django 6.1 on 2026-08-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='联系人电话')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='公司/品牌')),
                ('project_type', models.CharField(max_length=50, verbose_name='项目类型')),
                ('quantity', models.CharField(max_length=50, verbose_name='预计数量')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='交付城市')),
                ('budget', models.CharField(max_length=50, verbose_name='预算区间')),
                ('requirement', models.TextField(verbose_name='需求说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '联系表单',
                'verbose_name_plural': '联系表单',
                'db_table': 'contract',
            },
        ),
    ]
