# Generated by Django 6.1 on 2026-08-31 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '联络表单', 'verbose_name_plural': '联络表单'},
        ),
    ]
